name = "ExponentialQueues"
uuid = "8f3a112f-b142-4e59-ac86-373e9eb88260"
version = "1.1.1"
authors = ["Alfredo Braunstein"]

[deps]
CavityTools = "217fe2f1-7e3d-419f-9934-cd6900c2759a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Unrolled = "9602ed7d-8fef-5bc8-8597-8f21381861e8"

[compat]
CavityTools = "1.3"
Random = "1"
Unrolled = "0.1.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
